events {}

http {
    include /etc/nginx/mime.types;   # 🔥 THIS LINE FIXES YOUR ISSUE
    default_type application/octet-stream;

    server {
        listen 10000;

        root /app/frontend/dist;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://localhost:8000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }
    }
}